import './landing.css';

export function renderLanding() {
  return `<section class="lake-hero" id="lake-hero" aria-label="Дача на Байкале, бухта Максимиха">
    <div class="lake-scene" id="lake-scene"><img src="/media/maximikha.jpg" alt="Вечер в бухте Максимиха на Байкале" class="lake-fallback"></div>
    <div class="hero-shade"></div>
    <div class="hero-copy"><p class="hero-kicker">МАКСИМИХА. БАЙКАЛ. ВЫ.</p><h1>Дача<br><em>на Байкале</em></h1><div class="hero-caption"><p>Номера и отдельный домик в Максимихе.<br>Отдых в своём ритме.</p><a href="#book" class="hero-cta">Выбрать даты <i data-lucide="arrow-up-right"></i></a></div></div>
    <div class="hero-bottom"><button data-home-scroll="place" class="scroll-cue"><i data-lucide="arrow-down"></i>Открыть место</button><span>Восточный берег Байкала</span><button class="motion-toggle" id="motion-toggle" title="Приостановить анимацию" aria-label="Приостановить анимацию"><i data-lucide="pause"></i></button></div>
  </section>
  <section class="place-section" id="place"><div class="editorial-wrap"><div class="section-label"><span>01 / МЕСТО</span><span>Немного ближе к природе</span></div><div class="place-layout"><div class="place-copy reveal"><h2>Просто быть.<br><em>Здесь и сейчас.</em></h2><p>Утро без спешки. Чай во дворе. Разговоры на веранде. «Дача на Байкале» — небольшой гостевой дом в селе Максимиха, куда приезжают за своим спокойным отдыхом.</p><p class="place-secondary">Деревянные комнаты, отдельный двухместный домик и общий двор — для поездки вдвоём, с семьёй или своей компанией.</p><a class="editorial-link" href="#book">Найти своё место <i data-lucide="arrow-up-right"></i></a></div><figure class="place-image reveal"><img src="/photos/territory/photo7.jpg" alt="Двор и гостевой дом Дача на Байкале" loading="lazy"><figcaption><span>Наш дом в Максимихе</span><span>Дачная, 12</span></figcaption></figure></div><div class="place-facts"><div><strong>14</strong><span>спальных мест</span></div><div><strong>4</strong><span>варианта проживания</span></div><div><strong>14:00</strong><span>время заезда</span></div><p>Небольшое место.<br>Много личных воспоминаний.</p></div></div></section>
  <section class="stay-section" id="stay"><div class="editorial-wrap"><div class="section-label"><span>02 / ПРОЖИВАНИЕ</span><span>Вместе. Или только вдвоём.</span></div><div class="section-heading reveal"><h2>Ваше место<br><em>на Байкале.</em></h2><a class="editorial-link" href="#book">Все свободные даты <i data-lucide="arrow-up-right"></i></a></div><div class="stay-grid">
    ${[['2','Двухместный номер','Для двоих','/photos/2_room/photo3.jpg'],['5','Отдельный домик','Своё пространство','/photos/2_urta/photo_1.jpg'],['4','Четырёхместный номер','Для семьи','/photos/4_room/photo5.jpg'],['6','Шестиместный номер','Для своей компании','/photos/6_room/photo2.jpg']].map(([code,name,note,photo],i) => `<article class="stay-item reveal"><button class="stay-image" data-action="gallery" data-code="${code}" aria-label="Фотографии: ${name}"><img src="${photo}" alt="${name} в Даче на Байкале" loading="lazy"><span class="stay-photo-icon"><i data-lucide="arrow-up-right"></i></span></button><div class="stay-meta"><span>0${i+1} / ${note}</span><span>${code === '5' ? 2 : code} гостя</span></div><div class="stay-title"><h3>${name}</h3><a href="#book" aria-label="Забронировать: ${name}"><i data-lucide="arrow-up-right"></i></a></div></article>`).join('')}
  </div></div></section>
  <section class="moments-section" id="moments"><div class="editorial-wrap"><div class="section-label"><span>03 / ДАЧНАЯ ЖИЗНЬ</span><span>Счастье в простых вещах</span></div><div class="moments-heading reveal"><h2>Время,<br><em>которое ваше.</em></h2><p>Общий двор, беседка, место для вечерних разговоров. Здесь можно никуда не торопиться.</p></div><div class="moments-grid"><figure class="moment-large reveal"><img src="/photos/territory/photo6.jpg" alt="Солнечный двор гостевого дома" loading="lazy"><figcaption>Солнечные дни во дворе</figcaption></figure><figure class="moment-small reveal"><img src="/photos/territory/photo9.jpg" alt="Беседка для отдыха" loading="lazy"><figcaption>Вечера за общим столом</figcaption></figure></div></div></section>
  <section class="arrival-section" id="arrival"><div class="editorial-wrap"><div class="section-label"><span>04 / ВАША ПОЕЗДКА</span><span>Осталось выбрать даты</span></div><div class="arrival-layout"><div class="reveal"><h2>Увидимся<br><em>на Байкале.</em></h2><p>Село Максимиха, ул. Дачная, 12.<br>Заявку и детали проживания подтвердит администратор.</p><div class="arrival-actions"><a href="#book" class="hero-cta">Забронировать отдых <i data-lucide="arrow-up-right"></i></a><a href="tel:+79085948948" class="editorial-link">Позвонить Даниилу <i data-lucide="phone"></i></a></div></div><div class="faq reveal"><details><summary>Как забронировать проживание?<i data-lucide="plus"></i></summary><p>Выберите даты, гостей и вариант проживания. После отправки заявки администратор подтвердит доступность. Следить за статусом можно в личном кабинете.</p></details><details><summary>Как проходит оплата?<i data-lucide="plus"></i></summary><p>После подтверждения заявки внесите предоплату от 50% переводом и приложите чек в личном кабинете. Администратор проверит поступление денег.</p></details><details><summary>Можно приехать всей компанией?<i data-lucide="plus"></i></summary><p>Да. Можно выбрать несколько номеров или все 14 мест. Доступные сочетания и итоговая стоимость появятся при поиске по вашим датам.</p></details><details><summary>Во сколько заезд и выезд?<i data-lucide="plus"></i></summary><p>Заезд после 14:00, выезд до 12:00. Особые пожелания можно указать в комментарии к заявке.</p></details></div></div></div></section>
  <footer class="landing-footer"><div class="editorial-wrap"><div class="landing-footer-top"><span>Место для ваших воспоминаний.</span><a href="tel:+79085948948">+7 (908) 594-89-48 <i data-lucide="arrow-up-right"></i></a></div><div class="footer-wordmark">Дача на Байкале</div><div class="landing-footer-bottom"><span>Максимиха · Дачная, 12</span><button class="link" data-action="rules">Бронирование и отмена</button><a href="https://commons.wikimedia.org/wiki/File:Evening_in_the_Bay_Maximikha.jpg" target="_blank" rel="noopener noreferrer">Фото бухты: Аркадий Зарубин · CC BY-SA 3.0</a></div></div></footer>`;
}

export async function mountLanding() {
  const hero = document.querySelector('#lake-hero');
  const controller = new AbortController();
  document.querySelectorAll('[data-home-scroll]').forEach(button => button.addEventListener('click', () => document.getElementById(button.dataset.homeScroll)?.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth' }), { signal: controller.signal }));
  const observer = new IntersectionObserver(entries => entries.forEach(entry => { if (entry.isIntersecting) { entry.target.classList.add('revealed'); observer.unobserve(entry.target); } }), { threshold: .08 });
  document.querySelectorAll('.reveal').forEach(el => observer.observe(el));
  let disposeScene = () => {};
  try {
    const module = await import('./lake-scene.js');
    if (hero?.isConnected) disposeScene = module.mountLakeScene(hero, hero.querySelector('#lake-scene'));
  } catch { hero?.querySelector('#motion-toggle')?.setAttribute('hidden', ''); }
  return () => { controller.abort(); observer.disconnect(); disposeScene(); };
}
