from aiogram.fsm.state import State, StatesGroup


class BookingStates(StatesGroup):
    waiting_for_start_date = State()
    choosing_month_for_end_date = State()
    waiting_for_end_date = State()
    confirm_booking = State()
    waiting_for_contact = State()
    waiting_for_comment = State()
    waiting_for_comment_text = State()
    waiting_for_admin_response = State()
    waiting_for_user_response = State()
    waiting_for_review = State()
    waiting_for_cancellation_reason = State()
    waiting_for_support_message = State()
    waiting_for_payment_screenshot = State()
    waiting_for_admin_payment_confirmation_amount = State()
    viewing_photos = State()
    waiting_for_manual_contact = State()
    waiting_for_price_change_dates = State()
    waiting_for_price_change_value = State()
    waiting_for_price_change_start_date = State()
    waiting_for_price_change_end_date = State()
    waiting_for_availability_people = State()
    waiting_for_availability_duration = State()
    waiting_for_availability_room = State()
    viewing_availability_calendar = State()
    waiting_for_duration = State()
    waiting_for_adults = State()
    waiting_for_children = State()
    waiting_for_child_sleeping = State()
    waiting_for_room_type = State()
    waiting_for_bed_choice = State()
    waiting_for_full_name = State()
    waiting_for_rules_agreement = State()
    waiting_for_rules_prompt = State()
    waiting_for_update_file = State()
    waiting_for_admin_comment = State()
    waiting_for_admin_bookings_menu = State()
    viewing_admin_calendar = State()
    waiting_for_admin_booking_search = State()
    waiting_for_admin_booking_edit = State()
    waiting_for_blocked_dates_start = State()
    waiting_for_blocked_dates_end = State()
    waiting_for_guest_note = State()
    waiting_for_admin_create_people = State()
    waiting_for_admin_create_duration = State()
    waiting_for_admin_create_room = State()
    waiting_for_admin_create_start_date = State()
    waiting_for_admin_create_guest = State()
    waiting_for_admin_create_payment = State()
    waiting_for_admin_payment_update = State()
    waiting_for_admin_finance_update = State()
    waiting_for_admin_export_menu = State()
    waiting_for_admin_backup_menu = State()
    waiting_for_admin_backup_restore = State()
    waiting_for_admin_restart_confirm = State()
    waiting_for_guest_booking_edit = State()


class NewsStates(StatesGroup):
    waiting_for_news_content = State()
    waiting_for_news_media = State()
    waiting_for_news_action = State()
    waiting_for_news_edit = State()
